### ISSUE TITLE
unable to load model (neoforge 1.21.1)

### ISSUE THREAD

**Issue by VaporeonScripts** [bigenergy/glassential-renewed#10]
https://mclo.gs/PqDw4ul
![image](https://github.com/user-attachments/assets/4d16d3d5-c780-49a4-8a89-02fd3660d2ea)

**Comment by bigenergy** [comment]
thx for report, fixed in new version

**Comment by Taschenmogul** [comment]
The exact same bug exists in version 1.20.1-2.4.2. It's really just a "d" that got displaced, to spell "dreverse_oor" instead of "reverse_door", so fixing the error in the asset "assets/glassential/blockstates/dark_ethereal_reverse_door.json" and putting that into a datapack (or just using e.g. KubeJS's "asset"-folder for this) also fixes this issue; for anyone who might wish to make that happen for their own 1.20.1 modpack.

**Comment by bigenergy** [comment]
> The exact same bug exists in version 1.20.1-2.4.2. It's really just a "d" that got displaced, to spell "dreverse_oor" instead of "reverse_door", so fixing the error in the asset "assets/glassential/blockstates/dark_ethereal_reverse_door.json" and putting that into a datapack (or just using e.g. KubeJS's "asset"-folder for this) also fixes this issue; for anyone who might wish to make that happen for their own 1.20.1 modpack.

fixed in 2.4.3
